[bp] fix list and history
bp list and history was not working anymore because of the <div>
matching, which became a <p> in the HTML pages.

This patch replace the '//div[@class="infosynthese"]' by
'//p[@class="infosynthese"]' in order to fix the issue.

Previously woob was failing with:

2025-01-10 21:04:11,122:DEBUG:woob.backend.bp.browser:3.7:browser.py:787:iter_cards parsing 'https://voscomptesenligne.labanquepostale.fr/voscomptes/canalXHTML/CB/releveCB/preparerRecherche-mouvementsCarteDD.ea?typeListe=0'
2025-01-10 21:04:11,123:DEBUG:woob.core.bcall:3.7:bcall.py:92:backend_process <Backend bp>: Called function <bound method Application._do_complete of <woob.applications.bank.bank.Appbank object at 0x72397b429460>> raised an error: ValueError('not enough values to unpack (expected 1, got 0)')
Bug(bp): not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/.local/venvs/woob/lib/python3.12/site-packages/woob/core/bcall.py", line 88, in backend_process
    result = function(backend, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/venvs/woob/lib/python3.12/site-packages/woob/tools/application/base.py", line 348, in _do_complete
    res = getattr(backend, function)(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/woob/modules/bp/module.py", line 173, in iter_resources
    return self.iter_accounts()
           ^^^^^^^^^^^^^^^^^^^^
  File "/woob/modules/bp/module.py", line 75, in iter_accounts
    return self.browser.get_accounts_list()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/venvs/woob/lib/python3.12/site-packages/woob/browser/browsers.py", line 1157, in inner
    return func(browser, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/woob/modules/bp/browser.py", line 663, in get_accounts_list
    accounts.extend(self.iter_cards(account))
  File "/woob/modules/bp/browser.py", line 788, in iter_cards
    card = self.page.get_single_card(parent_id=account.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/woob/modules/bp/pages/accounthistory.py", line 228, in get_single_card
    div, = self.doc.xpath('//div[@class="infosynthese"]')
    ^^^^
ValueError: not enough values to unpack (expected 1, got 0)