[boursedirect] Handle new accounts URL
Some connections have a specific URL (listeContrats instead of compte).
Since this URL was not handled with a Page class, we were trying to
relogin but the self.login.go() was directly leading to AccountsPage,
resulting in the following error:
AccountsPage has no attribute 'do_login'.