enercoop: add labels for configuration value
Label is used and mandatory for backend configuration in CLI:

Configuration of backend enercoop
---------------------------------
[email] None:                                <=== HERE, we saw a None
     c: Run an external tool during backend load
     p: Prompt value when needed (do not store it)
     s: Store value in config
*** How do you want to store it? (c/P/s): s
Traceback (most recent call last):
  [...]
  File "woob/tools/application/base.py", line 460, in parse_args
    self._handle_options()
  File "woob/tools/application/repl.py", line 663, in _handle_options
    return super(ReplApplication, self)._handle_options()
  File "woob/tools/application/console.py", line 210, in _handle_options
    self.load_default_backends()
  File "woob/applications/bill/bill.py", line 65, in load_default_backends
    self.load_backends(CapDocument, storage=self.create_storage())
  File "woob/tools/application/repl.py", line 317, in load_backends
    return ConsoleApplication.load_backends(self, *args, **kwargs)
  File "woob/tools/application/console.py", line 143, in load_backends
    self.check_loaded_backends()
  File "woob/tools/application/console.py", line 153, in check_loaded_backends
    self.prompt_create_backends(default_config)
  File "woob/tools/application/console.py", line 189, in prompt_create_backends
    inst = self.add_backend(name, name, default_config)
  File "woob/tools/application/console.py", line 368, in add_backend
    params[key] = self.ask(value, default=params[key] if (key in params) else value.default)
  File "woob/tools/application/console.py", line 499, in ask
    question += ': '
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

That is perhaps not the best way to fix this bug. We could perhaps use
key name instead of label when label is not set